
/** Auto-generated by scripts/write-version.js — do not edit */
export const BUILD_INFO = {
  sha: "83fb10e",
  tag: "v0.1.0-ui-scaffold",
  branch: "0904/feedback-versioning",
  dirty: false,
  builtAt: "2025-09-04T10:02:28.203Z"
} as const;
